/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as RecenziaRouteImport } from './routes/recenzia'
import { Route as UcitelIdRouteImport } from './routes/ucitel.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RecenziaRoute = RecenziaRouteImport.update({
  id: '/recenzia',
  path: '/recenzia',
  getParentRoute: () => rootRouteImport,
} as any)
const UcitelIdRoute = UcitelIdRouteImport.update({
  id: '/ucitel/$id',
  path: '/ucitel/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/recenzia': typeof RecenziaRoute
  '/ucitel/$id': typeof UcitelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/recenzia': typeof RecenziaRoute
  '/ucitel/$id': typeof UcitelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/recenzia': typeof RecenziaRoute
  '/ucitel/$id': typeof UcitelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/recenzia' | '/ucitel/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/recenzia' | '/ucitel/$id'
  id: '__root__' | '/' | '/admin' | '/recenzia' | '/ucitel/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  RecenziaRoute: typeof RecenziaRoute
  UcitelIdRoute: typeof UcitelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recenzia': {
      id: '/recenzia'
      path: '/recenzia'
      fullPath: '/recenzia'
      preLoaderRoute: typeof RecenziaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ucitel/$id': {
      id: '/ucitel/$id'
      path: '/ucitel/$id'
      fullPath: '/ucitel/$id'
      preLoaderRoute: typeof UcitelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  RecenziaRoute: RecenziaRoute,
  UcitelIdRoute: UcitelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
